name: Android - Deploy Production build to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_android_production_to_firebase:
    name: Deploy android production to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Google Services
        env:
          ANDROID_PRODUCTION_GOOGLE_SERVICES_JSON: ${{ secrets.ANDROID_PRODUCTION_GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p android/src/production
          echo $ANDROID_PRODUCTION_GOOGLE_SERVICES_JSON > android/src/production/google-services.json

      - name: Setup Android release signing
        env:
          ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
          ANDROID_SIGNING_PROPERTIES: ${{ secrets.ANDROID_SIGNING_PROPERTIES }}
        run: |
          echo $ANDROID_RELEASE_KEYSTORE | base64 --decode > config/release.keystore
          echo $ANDROID_SIGNING_PROPERTIES | base64 --decode > signing.properties

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: android/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Build Production release APK
        run: ./gradlew assembleProductionRelease

      - name: Deploy staging to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '1:835959262689:android:cfc4c7eb6425a49c0896a0'
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_DISTRIBUTION_CREDENTIAL_JSON }}
          groups: nimble
          file: android/build/outputs/apk/production/release/android-production-release.apk
